"""Constants for Zidoo component."""
import logging
from .zidoorc import ZTYPE_VIDEO, ZTYPE_MOVIE, ZTYPE_TV_SHOW, ZTYPE_TV_SEASON,ZTYPE_TV_EPISODE,ZTYPE_COLLECTION,ZTYPE_OTHER
from homeassistant.components.media_player.const import (
    MEDIA_CLASS_ALBUM,
    MEDIA_CLASS_ARTIST,
    MEDIA_CLASS_GENRE,
    MEDIA_CLASS_DIRECTORY,
    MEDIA_CLASS_EPISODE,
    MEDIA_CLASS_MOVIE,
    MEDIA_CLASS_PLAYLIST,
    MEDIA_CLASS_TRACK,
    MEDIA_CLASS_SEASON,
    MEDIA_CLASS_TV_SHOW,
    MEDIA_CLASS_VIDEO,
    MEDIA_CLASS_URL,
    MEDIA_TYPE_MUSIC,
    MEDIA_TYPE_ALBUM,
    MEDIA_TYPE_ARTIST,
    MEDIA_TYPE_GENRE,
    MEDIA_TYPE_PLAYLIST,
    MEDIA_TYPE_TRACK,
    MEDIA_TYPE_SEASON,
    MEDIA_TYPE_MOVIE,
    MEDIA_TYPE_TVSHOW,
    MEDIA_TYPE_EPISODE,
    MEDIA_TYPE_VIDEO,
    MEDIA_TYPE_URL,
)
_LOGGER = logging.getLogger(__package__)

DOMAIN = "zidoo"
DATA_ZIDOO_CONFIG = "zidoo_config"
VERSION = "1.1.1"
DATA = "data"
UPDATE_TRACK = "update_track"
UPDATE_LISTENER = "update_listener"

MANUFACTURER = "Zidoo"

CLIENTID_PREFIX = "home-assistant"
CLIENTID_NICKNAME = "Home Assistant"

# Default Values
CONF_SHORTCUT = "shortcut_json"

MEDIA_TYPE_FILE = "file"

ITEM_TYPE_MEDIA_CLASS = {
    MEDIA_TYPE_ALBUM: MEDIA_CLASS_ALBUM,
    MEDIA_TYPE_ARTIST: MEDIA_CLASS_ARTIST,
    MEDIA_TYPE_EPISODE: MEDIA_CLASS_EPISODE,
    MEDIA_TYPE_MOVIE: MEDIA_CLASS_MOVIE,
    MEDIA_TYPE_PLAYLIST: MEDIA_CLASS_PLAYLIST,
    MEDIA_TYPE_SEASON: MEDIA_CLASS_SEASON,
    MEDIA_TYPE_TVSHOW: MEDIA_CLASS_TV_SHOW,
    MEDIA_TYPE_TRACK: MEDIA_CLASS_TRACK,
    MEDIA_TYPE_VIDEO: MEDIA_CLASS_VIDEO,
    MEDIA_TYPE_FILE: MEDIA_CLASS_DIRECTORY,
    MEDIA_TYPE_URL: MEDIA_CLASS_URL,
}

ZCONTENT_ITEM_TYPE = {
    0: MEDIA_TYPE_FILE,  # folder
    1: MEDIA_TYPE_TRACK,  # music
    2: MEDIA_TYPE_VIDEO,  # video
    # 3: 'image', # 4: 'text', # 5: 'apk', # 6: 'pdf', # 7: 'document', # 8: 'spreadsheet', # 9: 'presentation', # 10: 'web', # 11: 'archive' ,  # 12: 'other'
    1000: MEDIA_TYPE_FILE,  # hhd
    1001: MEDIA_TYPE_FILE,  # usb
    1002: MEDIA_TYPE_FILE,  # usb
    1003: MEDIA_TYPE_FILE,  # tf
    1004: MEDIA_TYPE_URL,  # nfs
    1005: MEDIA_TYPE_URL,  # smb
    1006: MEDIA_TYPE_FILE,
    1007: MEDIA_TYPE_FILE,
    1008: MEDIA_TYPE_FILE,
}

ZTYPE_MEDIA_CLASS = {
    ZTYPE_VIDEO: MEDIA_CLASS_VIDEO,
    ZTYPE_MOVIE: MEDIA_CLASS_MOVIE,
    ZTYPE_COLLECTION: MEDIA_CLASS_MOVIE,
    ZTYPE_TV_SHOW: MEDIA_CLASS_TV_SHOW,
    ZTYPE_TV_SEASON: MEDIA_CLASS_SEASON,
    ZTYPE_TV_EPISODE: MEDIA_CLASS_TRACK,  # MEDIA_CLASS_EPISODE, # no episode images with zidoo
    6: MEDIA_CLASS_TRACK, # Other
    7: MEDIA_CLASS_TRACK, # Dummy for +1
}

ZTYPE_MEDIA_TYPE = {
    ZTYPE_VIDEO: MEDIA_TYPE_VIDEO,
    ZTYPE_MOVIE: MEDIA_TYPE_MOVIE,
    ZTYPE_COLLECTION: MEDIA_TYPE_MOVIE,
    ZTYPE_TV_SHOW: MEDIA_TYPE_TVSHOW,
    ZTYPE_TV_SEASON: MEDIA_TYPE_SEASON,
    ZTYPE_TV_EPISODE: MEDIA_TYPE_EPISODE, # no episode images with zidoo
    ZTYPE_OTHER: MEDIA_TYPE_TRACK,
    7: MEDIA_CLASS_TRACK, # Dummy for +1
}
