search:
  name: Search Media
  description: Search movie library and display browser.
  target:
    entity:
      integration: zidoo
      domain: media_player
  fields:
    query_string:
      name: Search String
      description: Enter the keyword query string
      required: true
      example: "West Wing"
      selector:
        text:
    search_type:
      name: Search Type
      description: Override the media type ('video','movie','tvshow','music','artist','album')
      example: "tvshow"
      selector:
        text:
set_subtitle:
  name: Set Subtitle
  description: Set the subtitle index.
  target:
    entity:
      integration: zidoo
      domain: media_player
set_audio:
  name: Set Audio Track
  description: Set the audio track index.
  target:
    entity:
      integration: zidoo
      domain: media_player
send_key:
  name: Send Button Key
  description: "Send a button key event to the player."
  target:
    entity:
      integration: zidoo
      domain: media_player
  fields:
    key:
      name: Key Command
      description: "Enter button key command (see documentation for supported commands)"
      example: "Key.Back"
      required: true
      selector:
        text:
