search:
  name: Search Media
  description: Search movie library and display browser.
  target:
    entity:
      integration: zidoo
      domain: media_player
  fields:
    query_string:
      name: Search String
      description: Keyword query string
      required: true
      example: "West Wing"
      selector:
        text:
    video_type:
      name: Video Type
      description: Search Video Type ('movie','tvshow','other','hd','uhd','unlocked','kids')
      example: "tvshow"
      selector:
        text:
